[[gitoxide]]
arch = "aarch64"
git-tree-sha1 = "70596db861a5bec1855af498dbccda80f63f891b"
os = "macos"

    [[gitoxide.download]]
    sha256 = "63790a98c09bcf284a59e9849dd6c55422828376b626c3e2034f2231ce6d0e77"
    url = "https://github.com/JuliaBinaryWrappers/gitoxide_jll.jl/releases/download/gitoxide-v0.11.0+2/gitoxide.v0.11.0.aarch64-apple-darwin.tar.gz"
[[gitoxide]]
arch = "aarch64"
git-tree-sha1 = "66f51182bd07afb6537c3bef30e815a8c16b87df"
libc = "glibc"
os = "linux"

    [[gitoxide.download]]
    sha256 = "9c72cdf1a19fe408b03b7d10031f58034dac2299f00ac8544a44e52d75c5dfcb"
    url = "https://github.com/JuliaBinaryWrappers/gitoxide_jll.jl/releases/download/gitoxide-v0.11.0+2/gitoxide.v0.11.0.aarch64-linux-gnu.tar.gz"
[[gitoxide]]
arch = "aarch64"
git-tree-sha1 = "d2399e2a0695c542b7015ff95dbd9173d89e7edc"
libc = "musl"
os = "linux"

    [[gitoxide.download]]
    sha256 = "800149db8a13fd370850a21eeb5517d24fc3b0d4349c0f44dbe5595c0fd089e3"
    url = "https://github.com/JuliaBinaryWrappers/gitoxide_jll.jl/releases/download/gitoxide-v0.11.0+2/gitoxide.v0.11.0.aarch64-linux-musl.tar.gz"
[[gitoxide]]
arch = "i686"
git-tree-sha1 = "bbb8e79aeb8ab1d31729b0044823904e41101526"
libc = "glibc"
os = "linux"

    [[gitoxide.download]]
    sha256 = "de22b11599ad77e1f9f05ef5e82296a5deccb42f945754ba302e95414a0b6ac6"
    url = "https://github.com/JuliaBinaryWrappers/gitoxide_jll.jl/releases/download/gitoxide-v0.11.0+2/gitoxide.v0.11.0.i686-linux-gnu.tar.gz"
[[gitoxide]]
arch = "i686"
git-tree-sha1 = "adcb83b856b04e70d3acabf5544e1e3d17049c2c"
libc = "musl"
os = "linux"

    [[gitoxide.download]]
    sha256 = "794426905b49e42859de50d5c6ebb99e4522b9e145d423be436b2e83794203c7"
    url = "https://github.com/JuliaBinaryWrappers/gitoxide_jll.jl/releases/download/gitoxide-v0.11.0+2/gitoxide.v0.11.0.i686-linux-musl.tar.gz"
[[gitoxide]]
arch = "x86_64"
git-tree-sha1 = "d3a5afaa97e5801f71d0e73d163511c3971d1007"
os = "macos"

    [[gitoxide.download]]
    sha256 = "4ba7f635ff0eaee27dea44b595206dd7f1e29e5eb0b896a6cd799c37dc42ef4c"
    url = "https://github.com/JuliaBinaryWrappers/gitoxide_jll.jl/releases/download/gitoxide-v0.11.0+2/gitoxide.v0.11.0.x86_64-apple-darwin.tar.gz"
[[gitoxide]]
arch = "x86_64"
git-tree-sha1 = "f53bd3ae9e3ee77008737f96cb640e9f3419259a"
libc = "glibc"
os = "linux"

    [[gitoxide.download]]
    sha256 = "91be0ef8ed2b346197c74066f69e3dfe859c1cc7ccbc1fcaf0b845f53e6ffb5f"
    url = "https://github.com/JuliaBinaryWrappers/gitoxide_jll.jl/releases/download/gitoxide-v0.11.0+2/gitoxide.v0.11.0.x86_64-linux-gnu.tar.gz"
[[gitoxide]]
arch = "x86_64"
git-tree-sha1 = "7d299d658573751c24d2accca03272f1f9e6be3e"
libc = "musl"
os = "linux"

    [[gitoxide.download]]
    sha256 = "e348804c0af61f1c9f4fca4062211c7d71809f4da937379177438d229dfed1d8"
    url = "https://github.com/JuliaBinaryWrappers/gitoxide_jll.jl/releases/download/gitoxide-v0.11.0+2/gitoxide.v0.11.0.x86_64-linux-musl.tar.gz"
[[gitoxide]]
arch = "x86_64"
git-tree-sha1 = "c1043b24c7f653a5db9323f9f8d6178822c4f152"
os = "freebsd"

    [[gitoxide.download]]
    sha256 = "8ca106f018b30e85416361c2e45b543791a5ed71529fb88542079c2091b7d664"
    url = "https://github.com/JuliaBinaryWrappers/gitoxide_jll.jl/releases/download/gitoxide-v0.11.0+2/gitoxide.v0.11.0.x86_64-unknown-freebsd.tar.gz"
[[gitoxide]]
arch = "x86_64"
git-tree-sha1 = "7e77c49a38b0d186fcef242fdd95e8ffaeb8b350"
os = "windows"

    [[gitoxide.download]]
    sha256 = "0fb03dbe7ef46efffa8962df42dfbbaa926bf22be4bd9cd4b18ae0fb168f8ff3"
    url = "https://github.com/JuliaBinaryWrappers/gitoxide_jll.jl/releases/download/gitoxide-v0.11.0+2/gitoxide.v0.11.0.x86_64-w64-mingw32.tar.gz"
