[[gitoxide]]
arch = "aarch64"
git-tree-sha1 = "fe0b1daf5dc0e71ec8ef9d921d4ecc493aa387ec"
libc = "glibc"
os = "linux"

    [[gitoxide.download]]
    sha256 = "227ffa9d2684f295f6a2eb35958f771b5605a9ef3a604257364fb3bb53d92c47"
    url = "https://github.com/JuliaBinaryWrappers/gitoxide_jll.jl/releases/download/gitoxide-v0.11.0+1/gitoxide.v0.11.0.aarch64-linux-gnu.tar.gz"
[[gitoxide]]
arch = "aarch64"
git-tree-sha1 = "c36f1d1d3cffa507fc6e330ce5eaa7398f5723e8"
libc = "musl"
os = "linux"

    [[gitoxide.download]]
    sha256 = "a155050c58c7ba26e8e9e52c579e84e67248630405cdb678180eea5a16185803"
    url = "https://github.com/JuliaBinaryWrappers/gitoxide_jll.jl/releases/download/gitoxide-v0.11.0+1/gitoxide.v0.11.0.aarch64-linux-musl.tar.gz"
[[gitoxide]]
arch = "i686"
git-tree-sha1 = "20b465aa5dad1e1d27afd638f7648f48370b9b30"
libc = "glibc"
os = "linux"

    [[gitoxide.download]]
    sha256 = "a48cc116635d1938e058b9dbb7d1d6f3fcb938ee83806045860a87bb3ce1fa7e"
    url = "https://github.com/JuliaBinaryWrappers/gitoxide_jll.jl/releases/download/gitoxide-v0.11.0+1/gitoxide.v0.11.0.i686-linux-gnu.tar.gz"
[[gitoxide]]
arch = "i686"
git-tree-sha1 = "bc37206ae1e0d3b3a61bd42e1afbbc9c30e73b40"
libc = "musl"
os = "linux"

    [[gitoxide.download]]
    sha256 = "5720f5b0b5b18269468a54701c6fb5ebbf4e2306207b4fcd10bd223598f2e19c"
    url = "https://github.com/JuliaBinaryWrappers/gitoxide_jll.jl/releases/download/gitoxide-v0.11.0+1/gitoxide.v0.11.0.i686-linux-musl.tar.gz"
[[gitoxide]]
arch = "x86_64"
git-tree-sha1 = "7a91e75d0b60ad128ed8e3f23f4aa6e77c6b94f7"
libc = "glibc"
os = "linux"

    [[gitoxide.download]]
    sha256 = "921855e2afba01b4e66d479ae7160000b81765e3fb201361dad634cd428d5914"
    url = "https://github.com/JuliaBinaryWrappers/gitoxide_jll.jl/releases/download/gitoxide-v0.11.0+1/gitoxide.v0.11.0.x86_64-linux-gnu.tar.gz"
[[gitoxide]]
arch = "x86_64"
git-tree-sha1 = "7471b4d8a2aa4ef40397c38b5a31fce26229005e"
libc = "musl"
os = "linux"

    [[gitoxide.download]]
    sha256 = "a6e146fa9224d5a2f82c7ff091915754c6bc52842e75793f4881a5131d21e0b1"
    url = "https://github.com/JuliaBinaryWrappers/gitoxide_jll.jl/releases/download/gitoxide-v0.11.0+1/gitoxide.v0.11.0.x86_64-linux-musl.tar.gz"
[[gitoxide]]
arch = "x86_64"
git-tree-sha1 = "480615d05a1299cd91c919c9d2031b8d11501e3d"
os = "freebsd"

    [[gitoxide.download]]
    sha256 = "06dda6224cc808c6d3c468ceccd1a19a7b17a653b8511f829d2ea12123531a52"
    url = "https://github.com/JuliaBinaryWrappers/gitoxide_jll.jl/releases/download/gitoxide-v0.11.0+1/gitoxide.v0.11.0.x86_64-unknown-freebsd.tar.gz"
[[gitoxide]]
arch = "x86_64"
git-tree-sha1 = "8bcc0a9583475850d88c73e17f6c7826adcd3e7f"
os = "windows"

    [[gitoxide.download]]
    sha256 = "c44169dff28ed81c9b2cc1d38827b592259bdeb297218161895dc02d8ac49761"
    url = "https://github.com/JuliaBinaryWrappers/gitoxide_jll.jl/releases/download/gitoxide-v0.11.0+1/gitoxide.v0.11.0.x86_64-w64-mingw32.tar.gz"
